[alias]
miyoo = "zigbuild --profile miyoo --target armv7-unknown-linux-gnueabihf.2.17"

[target.armv7-unknown-linux-gnueabihf]
linker = "zig-cc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_PATH_armv7_unknown_linux_gnueabihf = "/usr/lib/arm-linux-gnueabihf/pkgconfig"
